export const productivityTable = [
  { id: 1, language: "ACCESS", low: 10, medium: 8, high: 6 },
  { id: 2, language: "ASP", low: 16, medium: 11, high: 6 },
  { id: 3, language: "ASPNET", low: 11, medium: 8, high: 5 },
  { id: 4, language: "ASSEMBLER", low: 18, medium: 12, high: 8 },
  { id: 5, language: "BASIC", low: 18, medium: 12, high: 8 },
  { id: 6, language: "C", low: 24, medium: 18, high: 12 },
  { id: 7, language: "C#", low: 17, medium: 12, high: 7 },
  { id: 8, language: "C++", low: 18, medium: 12, high: 8 },
  { id: 9, language: "CKAN", low: 18, medium: 14, high: 8 },
  { id: 10, language: "CLIPPER", low: 12, medium: 8, high: 6 },
  { id: 11, language: "COBOL", low: 14, medium: 10, high: 6 },
  { id: 12, language: "COMPONENTE – CÓDIGO PROPRIETÁRIO", low: 26, medium: 19, high: 12 },
  { id: 13, language: "COMPONENTE – CÓDIGO ABERTO", low: 26, medium: 19, high: 12 },
  { id: 14, language: "CSP", low: 16, medium: 10, high: 8 },
  { id: 15, language: "Dardo /Netuno", low: 18, medium: 14, high: 12 },
  { id: 16, language: "DATA DISCOVERY", low: 16, medium: 12, high: 6 },
  { id: 17, language: "DELPHI", low: 12, medium: 8, high: 6 },
  { id: 18, language: "Dot Net (.Net)", low: 14, medium: 12, high: 10 },
  { id: 19, language: "DW OUTRAS ( apenas OLAP) – Microstrategy, Power Center e etc", low: 14, medium: 10, high: 5 },
  { id: 20, language: "DW OUTRAS (Extração e OLAP) - Microstrategy, Power Center e etc", low: 16, medium: 12, high: 6 },
  { id: 21, language: "DW PENTAHO (Apenas OLAP)", low: 16, medium: 10, high: 6 },
  { id: 22, language: "DW PENTAHO (Extração e OLAP)", low: 18, medium: 12, high: 8 },
  { id: 23, language: "EXCEL", low: 6, medium: 5, high: 4 },
  { id: 24, language: "FORMS/REPORTS/ORACLE", low: 16, medium: 12, high: 6 },
  { id: 25, language: "HTML", low: 10, medium: 8, high: 4 },
  { id: 26, language: "JAVA", low: 14, medium: 10, high: 6 },
  { id: 27, language: "Java AndroMDA", low: 15, medium: 10, high: 5 },
  { id: 28, language: "Java Demoiselle V 1.0", low: 16, medium: 11, high: 6 },
  { id: 29, language: "Java Demoiselle V 2.0", low: 19, medium: 13, high: 7 },
  { id: 30, language: "Java Flex", low: 15, medium: 12, high: 8 },
  { id: 31, language: "Java Script", low: 16, medium: 12, high: 8 },
  { id: 32, language: "JCUPIM", low: 41, medium: 28, high: 15 },
  { id: 33, language: "Joomla", low: 18, medium: 14, high: 8 },
  { id: 34, language: "LASER XEROX", low: 30, medium: 20, high: 16 },
  { id: 35, language: "LIFERAY", low: 16, medium: 12, high: 8 },
  { id: 36, language: "LIGHTBASE", low: 18, medium: 12, high: 6 },
  { id: 37, language: "LOTUS NOTES", low: 8, medium: 6, high: 4 },
  { id: 38, language: "LTD", low: 18, medium: 13, high: 8 },
  { id: 39, language: "MIDDLEWARE", low: 26, medium: 19, high: 12 },
  { id: 40, language: "MOBILE - ANDROID", low: 18, medium: 14, high: 12 },
  { id: 41, language: "MOBILE - ANDROID E IOS", low: 18, medium: 14, high: 12 },
  { id: 42, language: "MOBILE - HTML 5 e JQUERY MOBILE", low: 18, medium: 14, high: 12 },
  { id: 43, language: "MOBILE - IOS", low: 18, medium: 14, high: 12 },
  { id: 44, language: "MOBILE - PHONEGAP", low: 18, medium: 14, high: 12 },
  { id: 45, language: "MOBILE – WINDOWS PHONE", low: 18, medium: 14, high: 12 },
  { id: 46, language: "NATURAL (Batch e On-Line)", low: 12, medium: 10, high: 8 },
  { id: 47, language: "Oracle Designer 2000", low: 12, medium: 6, high: 4 },
  { id: 48, language: "PENTAHO (Projetos PENTAHO Não BI)", low: 7, medium: 6, high: 5 },
  { id: 49, language: "PHP", low: 15, medium: 10, high: 5 },
  { id: 50, language: "PL/SQL de demais SGBDs", low: 11, medium: 9, high: 7 },
  { id: 51, language: "PROJETOS DE GEOPROCESSAMENTO", low: 27, medium: 19, high: 11 },
  { id: 52, language: "PROJETOS DE GEORREFERENCIAMENTO", low: 27, medium: 19, high: 11 },
  { id: 53, language: "PROJETOS DE WORKFLOW", low: 24, medium: 18, high: 16 },
  { id: 54, language: "PYTHON", low: 18, medium: 14, high: 8 },
  { id: 55, language: "RUBY ON RAILS", low: 18, medium: 14, high: 8 },
  { id: 56, language: "UNIX SHELL SCRIPTS", low: 18, medium: 14, high: 8 },
  { id: 57, language: "VB-SCRIPT", low: 16, medium: 14, high: 8 },
  { id: 58, language: "VISUAL BASIC /Crystal Reports", low: 12, medium: 8, high: 6 },
  { id: 59, language: "VISUAL C++", low: 16, medium: 14, high: 7 },
  { id: 60, language: "VISUAL GEN", low: 10, medium: 8, high: 6 },
  { id: 61, language: "VISUAL INTERDEV", low: 24, medium: 14, high: 8 },
  { id: 62, language: "VISUAL STUDIO .NET", low: 16, medium: 14, high: 12 },
  { id: 63, language: "WEBSERVICE", low: 20, medium: 15, high: 10 },
  { id: 64, language: "Workflow", low: 16, medium: 10, high: 8 }
];
